kind: pipeline
type: docker
name: default

workspace:
  base: E:\work\drone
  path: .

steps:
# 代码分析
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: tklin

trigger:
  branch:
    - master